extends: default
ignore: |
  apm.lock.yaml
  backstage/
rules:
  line-length: disable
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  indentation:
    indent-sequences: consistent
