# 環境 prod の Grafana (https://grafana-prod.<tailnet>.ts.net)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-prod
  namespace: prod
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: grafana
      port:
        number: 80
  tls:
    - hosts:
        - grafana-prod
